// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt0-nmfJvKbm0hc6tjgToJINfYSjbUnVs',
    appId: '1:1070340794068:web:494a28e8ec9f7be38a7d41',
    messagingSenderId: '1070340794068',
    projectId: 'flashryde-driver',
    authDomain: 'flashryde-driver.firebaseapp.com',
    databaseURL: 'https://flashryde-driver-default-rtdb.firebaseio.com',
    storageBucket: 'flashryde-driver.appspot.com',
    measurementId: 'G-B1Y4X9ZGGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClAalJHNBWWd8F3b-fvaq9whITTw3pMn4',
    appId: '1:1070340794068:android:bf85cf4b8d4c166b8a7d41',
    messagingSenderId: '1070340794068',
    projectId: 'flashryde-driver',
    databaseURL: 'https://flashryde-driver-default-rtdb.firebaseio.com',
    storageBucket: 'flashryde-driver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBisbn4hvkl2RzqT_FzQ8530Geq4Y0RJ1M',
    appId: '1:1070340794068:ios:8fe81bdc278e8de18a7d41',
    messagingSenderId: '1070340794068',
    projectId: 'flashryde-driver',
    databaseURL: 'https://flashryde-driver-default-rtdb.firebaseio.com',
    storageBucket: 'flashryde-driver.appspot.com',
    iosClientId: '1070340794068-vohoshv22tfk697a36907cno308b1c1r.apps.googleusercontent.com',
    iosBundleId: 'com.ugocode.fusersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBisbn4hvkl2RzqT_FzQ8530Geq4Y0RJ1M',
    appId: '1:1070340794068:ios:7af710811c6a78c38a7d41',
    messagingSenderId: '1070340794068',
    projectId: 'flashryde-driver',
    databaseURL: 'https://flashryde-driver-default-rtdb.firebaseio.com',
    storageBucket: 'flashryde-driver.appspot.com',
    iosClientId: '1070340794068-co7j6mf0fo1sjkrpbghkbb676k31h9pi.apps.googleusercontent.com',
    iosBundleId: 'com.example.fusersApp',
  );
}
